name: run-tests
run-name: ${{ github.actor }} is running tests
on: push
jobs:
  run-unittests:
    name: Run Unit Tests
    permissions:
      contents: read
    runs-on: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test model
        run: |
          python tests/test_model.py
      - name: Test modules
        run: |
          python tests/test_modules.py
